### ISSUE TITLE
Bug no Robô IFTTT

### ISSUE THREAD

**Issue by diegoeis** [kvnol/ofrontendacabou#3]
Ó, tem um bug lá no Robô do IFTTT... Por isso o front-end não pode acabar, o robo fica fazendo merda. Não consegue encontrar uma simples imagem. Fica subindo coisa quebrada pra produção. :-D

![screen shot 2018-07-16 at 21 17 49](https://user-images.githubusercontent.com/1918210/42789829-ce0dc74c-893d-11e8-9215-70d402200ce5.png)

**Comment by kvnol** [comment]
Opa! O bug foi arrumado no mesmo dia. Mas obrigado pela preocupação :smile:
